baseURL = "https://layandreas.github.io/personal-blog/"
title = "Personal Blog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Andreas Lay"
description = "Personal Blog"
keywords = [ "Blog", "Portfolio" ]
author = ""
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
hideFooter = true

  [params.assets]
  favicon = "/personal-blog/favicon.ico"
  favicon16x16 = "/personal-blog/favicon-16x16.png"
  favicon32x32 = "/personal-blog/favicon-32x32.png"
  apple_touch_icon = "/personal-blog/apple-touch-icon.png"
  #safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Andreas Lay"
  subtitle = "Data Scientist & Economist"
  imageUrl = "/personal-blog/profile.jpeg"
  imageWidth = 180
  imageHeight = 180
  imageTitle = ""

    [[params.profileMode.buttons]]
    name = "about"
    url = "about"

    [[params.profileMode.buttons]]
    name = "archive"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "categories"
    url = "categories"


  [params.homeInfoParams]
  Title = ""
  Content = ""

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/andreas-l-684252a4/"

  [[params.socialIcons]]
  name = "xing"
  url = "https://www.xing.com/profile/Andreas_Lay3/web_profiles"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/layandreas/personal-blog"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 990

[[menu.main]]
identifier = "archive"
name = "archive"
url = "/archives/"
weight = 1000

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 1010


[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 1020

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 1030

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 1040



[markup.highlight]
noClasses = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]
